account:
  msg: Welcome to the Heak bank account production application
  build-version: 3

  mailDetails:
    hostName: prod-account@mengheak.com
    port: 9000
    from: prod-account@mengheak.com
    subject: Your account details from Mengheak bank production environment

  activeBranches:
    - Kandal
    - Kompong Cham
    - Svay Rieng