services:
  configserver:
    image: heakbank/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - backend
    restart: unless-stopped
  account-service:
    image: heakbank/account:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - configserver
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  backend:
    name: heakbank_backend
    external: true
